<a href="https://colab.research.google.com/github/PiyushGithub24/MACHINE_LEARNING_BY_PIYUSH_KUMAR/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Multiple Linear Regression :-

In [73]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [74]:
x,y=make_regression(n_samples=100,n_features=2 ,n_informative=2 ,n_targets=1,noise=50)

In [75]:
x.shape ,y.shape

((100, 2), (100,))

In [76]:
df=pd.DataFrame({"Feature1 ":x[:,0],"Feature2 ":x[:,1],"Target ":y})

In [77]:
df.shape

(100, 3)

In [78]:
df.sample(5)

Feature1   Feature2     Target 
86  -0.090963   0.762097  79.040668
30   0.573289  -0.322036 -30.274311
27   1.174252   0.503518  57.791985
70  -1.307231  -1.263109  69.307861
20  -1.080134   0.588868  36.604700

In [79]:
fig=px.scatter_3d(df,x="Feature1 ",y="Feature2 ",z="Target ",color="Target ")
fig.show()

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [82]:
x_train.shape ,x_test.shape

((80, 2), (20, 2))

In [83]:
y_train.shape ,y_test.shape

((80,), (20,))

In [84]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [85]:
lr.fit(x_train,y_train)

LinearRegression()

In [86]:
y_pred=lr.predict(x_test)

In [87]:
y_test,y_pred

(array([ 59.8313669 , -30.2743112 ,  27.27732901, -75.74571137,
        -78.30996521, -19.19822614,  26.57190705,  57.79198501,
         53.93409169,  60.46615176, -17.90373181, -49.18284837,
        -92.39085037, -61.88495968, 150.56954754, -49.69429319,
        -69.90704746,  36.49416682,  39.76304946,  14.92511276]),
 array([ 79.54608132,  -6.28900156,  11.46723796, -27.13603746,
        -47.01489382, -22.18120736,   8.43075033,  39.25006261,
        -30.98435993,  62.20035568, -72.39776038, -37.39226331,
        -39.69929719, -38.15376919,  74.14456604, -63.42157176,
        -48.11558519,  29.84015259,  47.87251517,  25.34156431]))

In [88]:
print("MSE : ",mean_squared_error(y_test,y_pred))
print("MAE : ",mean_absolute_error(y_test,y_pred))
print("R2 : ",r2_score(y_test,y_pred))

MSE :  1281.1485630977438
MAE :  27.278229371218185
R2 :  0.6643761691731139


In [89]:
#this code is just for visualization :-
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T
z_final = lr.predict(final).reshape(10,10)

z = z_final


In [90]:
fig=px.scatter_3d(df,x="Feature1 ",y="Feature2 ",z="Target ")

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [91]:
lr.coef_

array([18.02422415, 42.04105515])

In [92]:
lr.intercept_

-3.083349578241884