<a href="https://colab.research.google.com/github/PiyushGithub24/MACHINE_LEARNING_BY_PIYUSH_KUMAR/blob/main/Iterative_Imputer_Using_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Iterative Imputer Using Sklearn :-

In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [2]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [3]:
df = df.iloc[:,0:-1]
df

R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [4]:
df.iloc[1,0] = np.NaN
df.iloc[3,1] = np.NaN
df.iloc[-1,-1] = np.NaN

<ipython-input-4-9e8f6afe97a9>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.NaN
<ipython-input-4-9e8f6afe97a9>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.NaN
<ipython-input-4-9e8f6afe97a9>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.NaN


In [5]:
df.head()

R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [9]:
lr=LinearRegression()
imputer = IterativeImputer(estimator=lr,max_iter=2,random_state=9)

In [7]:
imputer

IterativeImputer(estimator=LinearRegression(), random_state=9)

In [8]:
imputer.fit_transform(df)

array([[ 8.        , 15.        , 30.        ],
       [26.7182251 ,  5.        , 20.        ],
       [15.        , 10.        , 41.        ],
       [12.        , 13.02245793, 26.        ],
       [ 2.        , 15.        , 70.6926375 ]])

In [10]:
np.array(df)

array([[ 8., 15., 30.],
       [nan,  5., 20.],
       [15., 10., 41.],
       [12., nan, 26.],
       [ 2., 15., nan]])

In [11]:
def iter_impute(df,n_iter):
  lr=LinearRegression()
  imputer1 = IterativeImputer(estimator=lr,max_iter=n_iter-1,random_state=9)
  imputer2 = IterativeImputer(estimator=lr,max_iter=n_iter,random_state=9)
  return imputer2.fit_transform(df)-imputer1.fit_transform(df)

In [16]:
iter_impute(df,6)

/usr/local/lib/python3.10/dist-packages/sklearn/impute/_iterative.py:785: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(


array([[ 0.        ,  0.        ,  0.        ],
       [-0.00310996,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.00201914,  0.        ],
       [ 0.        ,  0.        ,  0.01278677]])