<a href="https://colab.research.google.com/github/PiyushGithub24/MACHINE_LEARNING_BY_PIYUSH_KUMAR/blob/main/Stochastic_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import time

In [ ]:
X,y=load_diabetes(return_X_y=True)

In [ ]:
X.shape ,y.shape

((442, 10), (442,))

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [ ]:
lr.intercept_

151.88331005254167

In [ ]:
y_pred=lr.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

#Lets create a class for Stochastic gradien descent :--

In [ ]:
class SGDRegressor:
  def __init__(self,Learning_rate=0.03,epochs=100):
    self.coef_=None
    self.intercept_=None
    self.lr=Learning_rate
    self.epochs=epochs

  def fit(self,X_train,y_train):
    #lets initialize the coefficients
    self.intercept_=0
    self.coef_=np.ones(X_train.shape[1])

    # print(self.intercept_ ,self.coef_)
    for i in range(self.epochs):
      for j in range(X_train.shape[0]):
        idx=np.random.randint(0,X_train.shape[0])

        y_hat=np.dot(X_train[idx],self.coef_) + self.intercept_

        inter_der=-2*(y_train[idx]-y_hat)
        self.intercept_=self.intercept_ -(self.lr*inter_der)

        coef_der=-2*np.dot((y_train[idx]-y_hat),X_train[idx])
        self.coef_=self.coef_ - (self.lr*coef_der)



    print(self.intercept_ ,'\n',self.coef_)

  def predict(self,X_test):
    return np.dot(X_test,self.coef_) + self.intercept_


In [ ]:
sgdr=SGDRegressor(Learning_rate=0.01,epochs=40)

In [ ]:
start=time.time()
sgdr.fit(X_train,y_train)
print("Time Taken :",time.time()-start)

153.94988552497642 
 [  50.35439299  -51.45188604  317.39019768  225.6914153    33.33280984
   -2.20317216 -169.11447043  141.6426023   291.56813466  120.10205255]
Time Taken : 0.2499103546142578


In [ ]:
y_pred=sgdr.predict(X_test)
r2_score(y_test,y_pred)

0.42256464644015146

#Lets use the SGDRegressor class from sklearn :-

In [ ]:
from sklearn.linear_model import SGDRegressor
reg=SGDRegressor(max_iter=100,learning_rate='constant',eta0=0.01)

In [ ]:
reg.fit(X_train,y_train)

SGDRegressor(learning_rate='constant', max_iter=100)

In [ ]:
reg.intercept_

array([151.966326])

In [ ]:
reg.coef_

array([  58.44053272,  -56.15386723,  329.98668641,  235.22819125,
         23.91407679,  -18.13087238, -167.16538466,  129.19396678,
        301.4019649 ,  128.08408149])

In [ ]:
y_pred=reg.predict(X_test)
r2_score(y_test,y_pred)

0.4271340650238912