<a href="https://colab.research.google.com/github/PiyushGithub24/MACHINE_LEARNING_BY_PIYUSH_KUMAR/blob/main/Mini_Batch_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mini Batch Gradient Desent Code From Scratch :--

In [165]:
import time
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [166]:
X,y=load_diabetes(return_X_y=True)

In [167]:
X.shape ,y.shape

((442, 10), (442,))

In [168]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [169]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [170]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [171]:
lr.intercept_

151.88331005254167

In [172]:
y_pred=lr.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

#Lets create a class for Mini Batch Gradien Descent :--

In [173]:
import random
ran_idx=random.sample(range(X_train.shape[0]),10)
ran_idx

[107, 80, 346, 231, 224, 287, 105, 12, 330, 56]

In [174]:
X_train[ran_idx]

array([[ 0.01628068, -0.04464164,  0.00133873,  0.00810098,  0.0053108 ,
         0.01089891,  0.03023191, -0.03949338, -0.04542404,  0.03205916],
       [-0.05637009, -0.04464164,  0.09295276, -0.01944183,  0.01494247,
         0.02342485, -0.02867429,  0.02545259,  0.02606052,  0.04034337],
       [ 0.01628068, -0.04464164,  0.02073935,  0.02187239, -0.01395254,
        -0.01321352, -0.00658447, -0.00259226,  0.01331691,  0.04034337],
       [ 0.05260606, -0.04464164, -0.00405033, -0.03090652, -0.0469754 ,
        -0.0583069 , -0.01394774, -0.02583997,  0.03606033,  0.02377494],
       [-0.07816532, -0.04464164, -0.04069594, -0.08141314, -0.10063757,
        -0.11279473,  0.02286863, -0.0763945 , -0.02029232, -0.05078298],
       [ 0.07076875,  0.05068012, -0.01698407,  0.02187239,  0.04383748,
         0.05630544,  0.03759519, -0.00259226, -0.07020936, -0.01764613],
       [-0.06363517,  0.05068012,  0.09618619,  0.10450081, -0.00294491,
        -0.00475851, -0.00658447, -0.00259226

In [175]:
class MBGDRegressor:
  def __init__(self,batch_size,Learning_rate=0.03,epochs=100):
    self.coef_=None
    self.intercept_=None
    self.batch_size=batch_size
    self.lr=Learning_rate
    self.epochs=epochs

  def fit(self,X_train,y_train):
    #lets initialize the coefficients
    self.intercept_=0
    self.coef_=np.ones(X_train.shape[1])

    # print(self.intercept_ ,self.coef_)
    for i in range(self.epochs):
      for j in range(int(X_train.shape[0]/self.batch_size)):
        idx=random.sample(range(X_train.shape[0]),self.batch_size)
        X_batch=X_train[idx]
        y_batch=y_train[idx]
        y_hat=np.dot(X_batch ,self.coef_) + self.intercept_

        intercept_der=-2 *np.mean(y_batch - y_hat)
        self.intercept_=self.intercept_  - (self.lr * intercept_der)

        coef_der=(-2)*np.dot((y_batch-y_hat),X_batch)/X_batch.shape[0]
        self.coef_=self.coef_-(self.lr*coef_der)
    print(self.intercept_ ,'\n',self.coef_)

  def predict(self,X_test):
    return np.dot(X_test,self.coef_) + self.intercept_


In [176]:
mbgd=MBGDRegressor(batch_size=20,Learning_rate=0.25,epochs=60)

In [177]:
mbgd.fit(X_train,y_train)

148.3867110983091 
 [  43.86432451  -98.75853757  415.88142566  282.86976506   -3.89775594
  -56.7048984  -190.70823322  122.92534571  368.56077891  122.03789402]


In [178]:
y_pred=mbgd.predict(X_test)
r2_score(y_test,y_pred)

0.44416841237492843

#Implementing Min Batch Gradient Descent using sklearn:-
- since for this we have to use SGDRegressor but we can not directly use SGDRegressor instead we use it by using partial_fit method:-

In [179]:
from sklearn.linear_model import SGDRegressor

In [180]:
reg=SGDRegressor(learning_rate='constant',eta0=0.25)

In [181]:
batch_size=35
for i in range(100):
  idx=random.sample(range(X_train.shape[0]),batch_size)
  X_batch=X_train[idx]
  y_batch=y_train[idx]
  reg.partial_fit(X_batch,y_batch)

In [182]:
reg.coef_

array([  -8.45370314, -131.52949825,  482.92121187,  301.19512058,
        -47.43742825, -130.85332907, -195.09640162,   98.29673612,
        443.98870182,   96.07702407])

In [183]:
reg.intercept_

array([151.72776461])

In [184]:
y_pred1=reg.predict(X_test)
r2_score(y_test,y_pred1)

0.4518827764191582