In [14]:
import pickle
import numpy as np

In [15]:
ohe_sex=pickle.load(open('model/ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('model/ohe_embarked.pkl','rb'))
clf=pickle.load(open('model/clf.pkl','rb'))

In [16]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [17]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [18]:
test_input[:,1].shape

(1,)

In [19]:
test_input[:,1].reshape(1,1)

array([['male']], dtype=object)

In [20]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [21]:
test_input_sex 

array([[0., 1.]])

In [22]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [23]:
test_input_embarked

array([[0., 0., 1.]])

In [24]:
test_input_age = test_input[:,2].reshape(1,1)

In [25]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)  
#this pattern should not be change.

In [26]:
test_input_transformed.shape

(1, 10)

In [27]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

In [30]:
print(clf.predict(test_input_transformed))

[1]


In [31]:
print(clf.predict(test_input_transformed)[0])

1
