# Naive Baye's Machine Learning Algorithms Implementation:

In [123]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [124]:
X,y=load_iris(return_X_y=True)

In [125]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [126]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Train test split:

In [127]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [128]:
X_train.shape ,X_test.shape,y_train.shape,y_test.shape

((112, 4), (38, 4), (112,), (38,))

### Importing and creating object of gausian naive baye's :

In [129]:
from  sklearn.naive_bayes import GaussianNB
gaussian=GaussianNB()

In [130]:
gaussian.fit(X_train,y_train)

GaussianNB()

In [131]:
y_pred=gaussian.predict(X_test)

In [132]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

### Checking the accuracy of the model :

In [133]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [134]:
print(confusion_matrix(y_pred,y_test))
print()
print(accuracy_score(y_pred,y_test))
print()
print(classification_report(y_pred,y_test))

[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]

1.0

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



## Tips dataset :

In [135]:
import seaborn as sns
tips=sns.load_dataset('tips')

In [136]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [137]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [138]:
X=tips[['total_bill','tip','sex','day','time','size']]
y=tips['smoker']

In [139]:
X

total_bill   tip     sex   day    time  size
0         16.99  1.01  Female   Sun  Dinner     2
1         10.34  1.66    Male   Sun  Dinner     3
2         21.01  3.50    Male   Sun  Dinner     3
3         23.68  3.31    Male   Sun  Dinner     2
4         24.59  3.61  Female   Sun  Dinner     4
..          ...   ...     ...   ...     ...   ...
239       29.03  5.92    Male   Sat  Dinner     3
240       27.18  2.00  Female   Sat  Dinner     2
241       22.67  2.00    Male   Sat  Dinner     2
242       17.82  1.75    Male   Sat  Dinner     2
243       18.78  3.00  Female  Thur  Dinner     2

[244 rows x 6 columns]

In [140]:
y

0       No
1       No
2       No
3       No
4       No
      ... 
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): ['Yes', 'No']

In [141]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [142]:
X_train.shape ,X_test.shape,y_train.shape,y_test.shape

((183, 6), (61, 6), (183,), (61,))

In [143]:
X_train

total_bill   tip     sex   day    time  size
58        11.24  1.76    Male   Sat  Dinner     2
1         10.34  1.66    Male   Sun  Dinner     3
2         21.01  3.50    Male   Sun  Dinner     3
68        20.23  2.01    Male   Sat  Dinner     2
184       40.55  3.00    Male   Sun  Dinner     2
..          ...   ...     ...   ...     ...   ...
64        17.59  2.64    Male   Sat  Dinner     3
15        21.58  3.92    Male   Sun  Dinner     2
228       13.28  2.72    Male   Sat  Dinner     2
125       29.80  4.20  Female  Thur   Lunch     6
9         14.78  3.23    Male   Sun  Dinner     2

[183 rows x 6 columns]

In [144]:
y_train

58     Yes
1       No
2       No
68      No
184    Yes
      ... 
64      No
15      No
228     No
125     No
9       No
Name: smoker, Length: 183, dtype: category
Categories (2, object): ['Yes', 'No']

In [145]:
X['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [146]:
X['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [147]:
X['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

### encoding on categorical columns:
- sex    -->label encoding
- time   -->label encoding
- smoker -->label encoding
- day    -->one hot encoding

In [148]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [149]:
X_train['sex'] = le1.fit_transform(X_train['sex'])     
X_train['time'] = le2.fit_transform(X_train['time'])
y_train = le3.fit_transform(y_train)

In [150]:
X_train

total_bill   tip  sex   day  time  size
58        11.24  1.76    1   Sat     0     2
1         10.34  1.66    1   Sun     0     3
2         21.01  3.50    1   Sun     0     3
68        20.23  2.01    1   Sat     0     2
184       40.55  3.00    1   Sun     0     2
..          ...   ...  ...   ...   ...   ...
64        17.59  2.64    1   Sat     0     3
15        21.58  3.92    1   Sun     0     2
228       13.28  2.72    1   Sat     0     2
125       29.80  4.20    0  Thur     1     6
9         14.78  3.23    1   Sun     0     2

[183 rows x 6 columns]

In [151]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0])

In [152]:
X_test['sex'] = le1.fit_transform(X_test['sex'])     
X_test['time'] = le2.fit_transform(X_test['time'])
y_test = le3.fit_transform(y_test)

### day -->one hot encoding

In [153]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [154]:
ct=ColumnTransformer([('OHE',OneHotEncoder(drop='first'),['day'])],
                     remainder='passthrough')

In [155]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train=ct.fit_transform(X_train)

In [156]:
X_train

array([[ 1.  ,  0.  ,  0.  , 11.24,  1.76,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.34,  1.66,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 21.01,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.23,  2.01,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 40.55,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  9.6 ,  4.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 34.81,  5.2 ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 20.53,  4.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 41.19,  5.  ,  1.  ,  1.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  , 15.06,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.82,  1.75,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 26.88,  3.12,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 18.78,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 31.27,  5.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 18.28,  4.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.

In [157]:
X_test=ct.transform(X_test)
X_test

array([[ 0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  3.21,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.89,  5.16,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 24.06,  3.6 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  7.56,  1.44,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 30.14,  3.09,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 16.49,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.

## trainig the Gaussian Naive Bayes algorithm :

In [160]:
from sklearn.naive_bayes import GaussianNB
gaussian=GaussianNB()

In [161]:
gaussian.fit(X_train,y_train)

GaussianNB()

In [162]:
y_pred=gaussian.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])

## Checking the accuracy of the model :

In [163]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [164]:
print(confusion_matrix(y_pred,y_test))
print()
print(accuracy_score(y_pred,y_test))
print()
print(classification_report(y_pred,y_test))

[[24 15]
 [ 9 13]]

0.6065573770491803

              precision    recall  f1-score   support

           0       0.73      0.62      0.67        39
           1       0.46      0.59      0.52        22

    accuracy                           0.61        61
   macro avg       0.60      0.60      0.59        61
weighted avg       0.63      0.61      0.61        61

