<a href="https://colab.research.google.com/github/PiyushGithub24/MACHINE_LEARNING_BY_PIYUSH_KUMAR/blob/main/Column_Transformer(Date_15_06_24).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Column Transformer :-

In [55]:
import pandas as pd
import numpy as np

In [56]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [57]:
covid=pd.read_csv('covid_toy.csv')
covid

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [58]:
covid.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(covid.drop(columns=['has_covid']),covid['has_covid'],
                                                test_size=0.2)

In [60]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((80, 5), (20, 5), (80,), (20,))

In [61]:
x_train

age  gender  fever   cough       city
63   10    Male  100.0    Mild  Bangalore
36   38  Female  101.0    Mild  Bangalore
33   26  Female   98.0    Mild    Kolkata
28   16    Male  104.0    Mild    Kolkata
19   42  Female    NaN  Strong  Bangalore
..  ...     ...    ...     ...        ...
29   34  Female    NaN  Strong     Mumbai
61   81  Female   98.0  Strong     Mumbai
80   14  Female   99.0    Mild     Mumbai
68   54  Female  104.0  Strong    Kolkata
57   49  Female   99.0  Strong  Bangalore

[80 rows x 5 columns]

In [62]:
y_train

63     No
36     No
33     No
28     No
19    Yes
     ... 
29    Yes
61     No
80    Yes
68     No
57     No
Name: has_covid, Length: 80, dtype: object

#Aam zindagi ,ie,without ColumnTransformer :

In [63]:
# adding simple imputer to fever col
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])

# also the test data
x_test_fever = si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [64]:
x_train_fever

array([[100.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [100.91428571],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [103.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [100.91428571],
       [103.        ],
       [103.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [100.91428571],
       [101.        ],
       [102.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [103.        ],
       [100.91428571],
       [102.        ],
       [100.        ],
       [100.91428571],
       [101.        ],
       [101.        ],
       [100.91428571],
       [ 99.        ],
       [103.        ],
       [101.        ],
       [100.91428571],
       [101.        ],
       [104.        ],
       [102.        ],
       [104.        ],
       [ 98.        ],
       [104

In [65]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [66]:
x_test_cough

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.]])

In [67]:
x_train['city'].unique()

array(['Bangalore', 'Kolkata', 'Delhi', 'Mumbai'], dtype=object)

In [68]:
x_train['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [69]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [70]:
x_test

age  gender  fever   cough       city
48   66    Male   99.0  Strong  Bangalore
62   56  Female  104.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
72   83  Female  101.0    Mild    Kolkata
49   44    Male  104.0    Mild     Mumbai
67   65    Male   99.0    Mild  Bangalore
93   27    Male  100.0    Mild    Kolkata
65   69  Female  102.0    Mild  Bangalore
18   64  Female   98.0    Mild  Bangalore
75    5    Male  102.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
82   24    Male   98.0    Mild    Kolkata
55   81  Female  101.0    Mild     Mumbai
20   12    Male   98.0  Strong  Bangalore
42   27    Male  100.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
2    42    Male  101.0    Mild      Delhi
54   60  Female   99.0    Mild     Mumbai
24   13  Female  100.0  Strong    Kolkata
8    19  Female  100.0  Strong  Bangalore

In [71]:
x_test_gender_city

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [72]:
# Extracting Age
x_train_age = x_train[['age']].values

# also the test data
x_test_age = x_test[['age']].values

x_train_age.shape

(80, 1)

In [73]:
x_test_age

array([[66],
       [56],
       [75],
       [83],
       [44],
       [65],
       [27],
       [69],
       [64],
       [ 5],
       [65],
       [24],
       [81],
       [12],
       [27],
       [68],
       [42],
       [60],
       [13],
       [19]])

In [74]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

x_train_transformed.shape

(80, 7)

In [75]:
for i in x_train.columns:
  print(i)

age
gender
fever
cough
city


In [76]:
x_test_transformed

array([[ 66.,  99.,   1.,   0.,   0.,   0.,   1.],
       [ 56., 104.,   0.,   0.,   0.,   0.,   1.],
       [ 75., 104.,   0.,   1.,   0.,   0.,   1.],
       [ 83., 101.,   0.,   0.,   1.,   0.,   0.],
       [ 44., 104.,   1.,   0.,   0.,   1.,   0.],
       [ 65.,  99.,   1.,   0.,   0.,   0.,   0.],
       [ 27., 100.,   1.,   0.,   1.,   0.,   0.],
       [ 69., 102.,   0.,   0.,   0.,   0.,   0.],
       [ 64.,  98.,   0.,   0.,   0.,   0.,   0.],
       [  5., 102.,   1.,   0.,   1.,   0.,   0.],
       [ 65., 101.,   0.,   0.,   0.,   1.,   0.],
       [ 24.,  98.,   1.,   0.,   1.,   0.,   0.],
       [ 81., 101.,   0.,   0.,   0.,   1.,   0.],
       [ 12.,  98.,   1.,   0.,   0.,   0.,   1.],
       [ 27., 100.,   1.,   1.,   0.,   0.,   0.],
       [ 68., 101.,   0.,   1.,   0.,   0.,   1.],
       [ 42., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 60.,  99.,   0.,   0.,   0.,   1.,   0.],
       [ 13., 100.,   0.,   0.,   1.,   0.,   1.],
       [ 19., 100.,   0.,   0.,

In [77]:
x_test_transformed=pd.DataFrame(x_test_transformed,columns=['age','fever','cough','gender_male','city_Kolkata','city_Bangalore','city_Delhi'])
x_train_transformed=pd.DataFrame(x_train_transformed ,columns=['age','fever','cough','gender_male','city_Kolkata','city_Bangalore','city_Delhi'])
x_test_transformed

age  fever  cough  gender_male  city_Kolkata  city_Bangalore  city_Delhi
0   66.0   99.0    1.0          0.0           0.0             0.0         1.0
1   56.0  104.0    0.0          0.0           0.0             0.0         1.0
2   75.0  104.0    0.0          1.0           0.0             0.0         1.0
3   83.0  101.0    0.0          0.0           1.0             0.0         0.0
4   44.0  104.0    1.0          0.0           0.0             1.0         0.0
5   65.0   99.0    1.0          0.0           0.0             0.0         0.0
6   27.0  100.0    1.0          0.0           1.0             0.0         0.0
7   69.0  102.0    0.0          0.0           0.0             0.0         0.0
8   64.0   98.0    0.0          0.0           0.0             0.0         0.0
9    5.0  102.0    1.0          0.0           1.0             0.0         0.0
10  65.0  101.0    0.0          0.0           0.0             1.0         0.0
11  24.0   98.0    1.0          0.0           1.0             0.0         0.0
12  81.0  101.0    0.0          0.0           0.0             1.0         0.0
13  12.0   98.0    1.0          0.0           0.0             0.0         1.0
14  27.0  100.0    1.0          1.0           0.0             0.0         0.0
15  68.0  101.0    0.0          1.0           0.0             0.0         1.0
16  42.0  101.0    1.0          1.0           0.0             0.0         0.0
17  60.0   99.0    0.0          0.0           0.0             1.0         0.0
18  13.0  100.0    0.0          0.0           1.0             0.0         1.0
19  19.0  100.0    0.0          0.0           0.0             0.0         1.0

#Mentos Zindagi :-

In [78]:
from sklearn.compose import ColumnTransformer

In [79]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [81]:
x_train_transformed=transformer.fit_transform(x_train)
x_test_transformed=transformer.transform(x_test)
x_train_transformed.shape ,x_test_transformed.shape

((80, 7), (20, 7))

In [82]:
x_test_transformed

array([[ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  65.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [101.,   0.,   0.,   0.,   0.,   1.,  65.],
       [ 98.,   0.,   1.,   0.,   1.,   0.,  24.],
       [101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [101.,   1.,   0.,   1.,   0.,   0.,  68.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [100.,   1.,   0.,   0.,   1.,   0.,  13.],
       [100.,   1.,   0.,   0.,